### PR TITLE
Supports react-gettext-parser's trimming options

### PR DESCRIPTION
**Pull request by alexanderwallin**
It's now possible to specify the `trim`, `trimLines` and `trimNewlines` configs in `.narprc`.

If you fancy an example of the mighty evil of mutability, https://github.com/laget-se/narp/commit/3e853d4f9a287c372c545d175dadb8130c2338fb is a treat.

### CODE REVIEW

**Comment by ridderholt** [comment]
@alexanderwallin Do we change any default behavior for narp by merging this PR?

**Comment by alexanderwallin** [comment]
I tried to think of a scenario where we would, but couldn't come up with any. I guess if you've done some wacko stuff like:

```js
// .narprc
{
  "extract": {
    "componentPropsMap": {
      "crayCray": "That is magically added to react-gettext-parser's defaults"
    }
  }
}

// my-script.js
const narp = require('narp')
const { GETTEXT_COMPONENT_PROPS_MAP } = require('react-gettext-parser')

// Run narp here
narp.push()

// Then depend on the contents of the react-gettext-parser defaults
for (const componentName in Object.keys(GETTEXT_COMPONENT_PROPS_MAP)) {
  // This will try to require path/to/components/crayCray.js
  const ComponentClass = require(`path/to/components/${componentName}.js`)
}
```

then it's gonna blow. But then you also had it coming. :)

**Comment by ridderholt** [comment]
@alexanderwallin Cool, do we need to do something in `package.json` to use the new version of `react-gettext-parser` that supports these features?

**Comment by alexanderwallin** [comment]
Yes, good catch! It's been updated now.

**Pull request merged**
