### PR TITLE
Supports using either Transifex or POEditor as a translation vendor

### PR DESCRIPTION
**Pull request by alexanderwallin**
By extracting everything vendor specific into internal plugins (`src/vendors`), this PR makes it possible to use either Transifex or POEditor.

Also, there is an emoji in on of the commit messages. That's so in the times.

### CODE REVIEW

**Comment by alexanderwallin** [comment]
This'd be major bumpin'

**Comment by alexanderwallin** [comment]
🎈

**Comment by ridderholt** [comment]
@alexanderwallin I have looked at the code and as far as I can tell there is nothing to complain about. However I think since this will be a breaking change (the .narprc for example should be changed in order for this version to work) there should be some sort of guide in the Readme pointing out the changes that needs to be made.

**Comment by alexanderwallin** [comment]
That is a fair point! I'll add that in.

**Comment by alexanderwallin** [comment]
@ridderholt There we are! See what you think.

**Comment by ridderholt** [comment]
@alexanderwallin Nice great work! 🥇 
Will merge this and publish to npm ASAP!

**Comment by alexanderwallin** [comment]
Sweet!

**Pull request merged**
